#!/bin/bash
convert() {
    filename=$(basename "$1")
    extension="${filename##*.}"
    filename="${filename%.*}"
    "$2"/ffmpeg -i "$1" "output/$filename.wav"
    echo "Conversion Complete!"
}
# get current dir
currentDir=$(dirname "$0")
echo $currentDir;
cd "$currentDir";
# convert vid
for f in *.mp4;
do
    convert "$f" "$currentDir"
done